package com.example.mydemok.application

/**
 * Created by magic-lee on 12/6/15.
 */
object Schema {
    const val SCHEMA_PREFIX = "xmnews://"
    const val SCHEMA_SPACE = "xmnews://space/content/"
    const val SCHEMA_NEWS_PAGE = "xmnews://zdg/"
    const val SCHEMA_LIFE_PAGE = "xmnews://strategy/"
    const val SCHEMA_MERCHANT_PAGE = "xmnews://merchant/"
    const val SCHEMA_IMAGE_PAGE = "xmnews://image/"
    const val SCHEMA_VIDEO_PAGE = "xmnews://video/"
    const val SCHEMA_COMMENT_PAGE = "xmnews://comments/"
    const val SCHEMA_BROWSER_URL = "xmnews://browser?url="
    const val SCHEMA_SHARE_SINA = "xmnews://share/sina"
    const val SCHEMA_SHARE_FRIEND = "xmnews://share/wxfriend"
    const val SCHEMA_SHARE_WECHAT = "xmnews://share/weixin"
    const val SCHEMA_SHARE_QQ = "xmnews://share/qq"
    const val SCHEMA_PHONE = "xmnews://phone/"
    const val SCHEMA_GET_SHARE = "xmnews://share/info"
    const val SCHEMA_MAP = "xmnews://map/"
    const val SCHEMA_ADD_LOVE = "xmnews://love/"
    const val SCHEMA_REPORT_COMMENT = "xmnews://comment/report/"
    const val SCHEMA_DEL_LOVE = "xmnews://notLove/"
    const val SCHEMA_SHOP = "xmnews://shop/"
    const val SCHEMA_GET_USER = "xmnews://get/user"
    const val SCHEMA_SHARE_IMG = "xmnews://share/saveimg/url"
    const val SCHEMA_FINISH = "xmnews://finish"

    // flnews://detail/government/[cid]?url=[contentUrl]&commentTourist=[commentTourist]
    const val SCHEMA_GOVERNMENT_DETAIL = "xmnews://detail/government"
    const val SCHEMA_GOVERNMENT_SEND = "xmnews://detail/government/send"
    const val SCHEMA_ACTIVITY_DETAIL = "xmnews://detail/activity"
    const val SCHEMA_COMMENT_ACTIVITY = "xmnews://detail/activity/comment"
    const val SCHEMA_COMMENT_GOVERNMENT = "xmnews://detail/government/comment"
    const val SCHEMA_DEPARTMENT_LIST = "xmnews://department/newsList"
    const val SCHEMA_DEPARTMENT_CONTENT = "xmnews://department/content"

    // flnews://image/government/[index]?url=[imageList]
    const val SCHEMA_GOVERNMENT_IMAGE_DETAIL = "xmnews://image/government"
    const val SCHEMA_NEWS_COMMENT = "xmnews://detail/zdg/comment"
    const val SCHEMA_NEWS_SCORE = "xmnews://score"
    const val ADD_SCORE = "xmnews://addScore"
    const val SCHEMA_SCORELIST = "xmnews://scoreList"
    const val SCHEMA_ADDSCORELIST = "xmnews://addScoreList"
    const val SCHEMA_RECOMMEND = "xmnews://recommend"
    const val SCHEMA_MERCHANT = "xmnews://merchant"
    const val SCHEMA_SAVE_IMAGE = "xmnews://content_image"
    const val SCHEMA_HIDE = "xmnews://hiddenCommentButton"
    const val SCHEMA_SHOW = "xmnews://showCommentButton"
    const val SCHEMA_GOTOINDEX = "xmnews://user/index"
    const val SCHEMA_REPLYCOMMENT = "xmnews://detail/radiopeanut/comment"
    const val SCHEMA_WX_MINI = "xmnews://mini"
    const val SCHEMA_URL = "zgdnativebrowser://"
    const val SCHEMA_PHOTO = "xmnews://space/detail/"
    const val SCHEMA_LIVE_INDEX = "xmnews://liveshow/index"
    const val SCHEMA_LIVE_DETAIL = "xmnews://liveshow/detail/"
    const val SCHEMA_ACTION_SCAN = "xmnews://common/openQR/"
    const val SCHEMA_ACTION_CLOSE = "xmnews://common/close"
    const val SCHEMA_ACTION_SHARE_WX = "xmnews://common/shareWM/"
    const val SCHEMA_NEWS_AWARD = "xmnews://new_score"
    const val SCHEMA_NEWS_AWARDLIST = "xmnews://new_scoreList"
}